# Generated by Django 5.1.4 on 2025-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temp',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
