# Generated by Django 5.1.4 on 2025-01-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='temp',
        ),
    ]
